version: 0.2

phases:
#  install:
#    runtime-versions:
#      java: corretto8

  pre_build:
    commands:
      #- #grails-2.5.6
      - echo build pre............
      - java -version
#      - wget -o grails-2.5.6.zip https://github.com/grails/grails-core/releases/download/v2.5.6/grails-2.5.6.zip
      #- if ! ls -A usr/local/grails-2.5.6/ | grep -q "."; then wget -o grails-2.5.6.zip https://github.com/grails/grails-core/releases/download/v2.5.6/grails-2.5.6.zip && unzip -q grails-2.5.6.zip.1 -d /usr/local; fi
#      - unzip -q grails-2.5.6.zip.1 -d /usr/local
      - ls /usr/local/grails-2.5.6/
      -  grails -version
#      - export PATH="usr/local/grails-2.5.6/bin:$PATH"
      #- ls /root/.m2/repository


  build:
    commands:
      - echo Build started on `date`
      - echo building the Jar file
      - /usr/local/grails-2.5.6/bin/grails war
  post_build:
    commands:
      - echo build end.............
      - ls /root/.m2/repository
artifacts:
  files:
    - target/web.war

cache:
  paths:
    - '/root/.m2/**/*'
    - '/usr/local/grails-2.5.6/**/*'