version: 0.2

phases:
  pre_build:
    commands:
      #- #grails-2.5.6
      - echo build pre............
      - java -version
      - wget -o grails-2.5.6.zip https://github.com/grails/grails-core/releases/download/v2.5.6/grails-2.5.6.zip
      - ls
      - unzip -q grails-2.5.6.zip.1 -d /usr/local
      - export PATH="usr/local/grails-2.5.6/bin:$PATH"



  build:
    commands:
      - echo Build started on `date`
      - echo building the Jar file
      - /usr/local/grails-2.5.6/bin/grails war
  post_build:
    commands:
      - echo build end.............
      - ls /root/.m2
artifacts:
  files:
    - target/web.war

cache:
  paths:
    - '/root/.m2/**/*'