version: 0.2

phases:
  pre_build:
    commands:
      #- #grails-2.5.6
      - echo build pre............
      - java -version
      - unzip -q grails-2.5.6.zip -d /usr/local
      - ll /usr/local
      - wget -o /usr/local/grails-2.5.6.zip https://github.com/grails/grails-core/releases/download/v2.5.6/grails-2.5.6.zip
      - unzip -q usr/local/grails-2.5.6.zip -d /usr/local
      - export PATH "usr/local/grails-2.5.6/bin:$PATH"

  build:
    commands:
      - echo Build started on `date`
      - echo building the Jar file
      - /usr/local/grails-2.5.6/bin/grails war
  post_build:
    commands:
      - echo build end............
artifacts:
  files:
    - target/web.war

